add tests bcond (requires root)
at least one test did:

mount: only root can use "--options" option
subprocess.CalledProcessError: Command '['flock', 'zdtm_mount_cgroups.lock', './zdtm_mount_cgroups']' returned non-zero exit st atus 1